name: Chocomin
id: chocomin
vibversion: 1.0.0
stages:
- id: build
  base: ghcr.io/vanilla-os/desktop:dev
  addincludes: true
  singlelayer: false
  labels:
    maintainer: Vanilla OS Contributors
  args:
    DEBIAN_FRONTEND: noninteractive
  runs:
    commands:
      - echo 'APT::Install-Recommends "1";' > /etc/apt/apt.conf.d/01norecommends

  modules:
  - name: remove-gnome-install-cinnamon
    type: shell
    commands:
    - /usr/bin/apt update
    - >-
      /usr/bin/apt purge --autoremove -y gdm3 nautilus gnome-core gnome-essentials
      gnome-control-center gnome-common gnome-software-vso-plugin gnome-backgrounds gjs
      libgirepository-1.0-1 gir1.2-gnomebluetooth-3.0 gir1.2-glib-2.0 gir1.2-gtk-3.0 gir1.2-gmenu-3.0 || true
    - /usr/bin/apt -y install lightdm cinnamon-desktop-environment
    - xdg-mime default nemo.desktop inode/directory
    - /usr/bin/apt -y install gnome-software

  - name: configure-desktop
    type: shell
    commands:
    - mkdir -p /etc/systemd/system/multi-user.target.wants/
    - ln -s /usr/lib/systemd/system/fix-gdm-permissions.service /etc/systemd/system/multi-user.target.wants/
    - sed -i 's/gdm/lightdm/g' /usr/lib/systemd/system/fix-gdm-permissions.service
    - rm /usr/lib/*/gnome-software/plugins-*/libgs_plugin_packagekit.so
    - rm -f /usr/share/applications/com.raggesilver.BlackBox.desktop

  - name: cleanup
    type: shell
    commands:
    - /usr/bin/apt autoremove -y
    - /usr/bin/apt clean
    - lpkg --lock

  - name: sysconf-setup
    type: shell
    commands:
      - rsync -a /etc/ /sysconf/

  - name: fsguard
    type: fsguard
    CustomFsGuard: false
    FsGuardLocation: "/usr/sbin/FsGuard"
    GenerateKey: true
    FilelistPaths: ["/usr/bin"]
    modules:
      - name: remove-prev-fsguard
        type: shell
        commands:
          - rm -rf /FsGuard
          - rm -f ./minisign.pub ./minisign.key
          - chmod +x /usr/share/init.d/010-fsguard.sh

  - name: cleanup2
    type: shell
    commands:
      - rm -rf /tmp/*
      - rm -rf /var/tmp/*
      - rm -rf /sources
