name: Vib Build (Podman)

on:
  push:
    branches:
      - 'dev'
    tags:
      - '*'
  workflow_dispatch:
  pull_request:

env:
  BUILDX_NO_DEFAULT_ATTESTATIONS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set tag for release builds
      if: ${{ github.ref_type == 'tag' }}
      run: |
        sed 's/ghcr.io\/vanilla-os\/core:dev/ghcr.io\/vanilla-os\/core:main/' -i recipe.yml

    - name: Build with vib and Podman
      uses: vanilla-os/vib-gh-action@main
      with:
        recipe: 'recipe.yml'
        plugins: 'Vanilla-OS/vib-fsguard:v1.6.1'

    - uses: actions/upload-artifact@v4
      with:
         name: Containerfile
         path: Containerfile

    - name: Generate image name
      id: generate_image_name
      run: |
        REPO_OWNER_LOWERCASE=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
        echo "REPO_OWNER_LOWERCASE=$REPO_OWNER_LOWERCASE" >> "$GITHUB_ENV"
        echo "IMAGE_URL=ghcr.io/$REPO_OWNER_LOWERCASE/desktop" >> "$GITHUB_ENV"

    - name: Login to GitHub Package Registry with Podman
      uses: redhat-actions/podman-login@v1
      if: ${{ github.event_name != 'pull_request' }}
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io

    - name: Build and Push the Podman image
      id: push
      run: |
        TAGS=""
        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          TAGS+="--tag ${{ env.IMAGE_URL }}:$(echo ${{ github.ref_name }} | sed 's/v//') "
          TAGS+="--tag ${{ env.IMAGE_URL }}:$(echo ${{ github.ref_name }} | sed -E 's/v?([0-9]+\.[0-9]+)\.[0-9]+/\1/') "
        else
          BRANCH_NAME=$(echo ${{ github.ref_name }} | sed 's/refs\/heads\///g')
          TAGS+="--tag ${{ env.IMAGE_URL }}:$BRANCH_NAME "
        fi
        
        podman build --file Containerfile ${TAGS} --platform linux/amd64 .

        if [[ "${{ github.event_name }}" != "pull_request" ]]; then
          podman push ${TAGS} --all
          DIGEST=$(podman images --digests --format "{{.Digest}}" | head -n 1)
          echo "digest=${DIGEST}" >> $GITHUB_OUTPUT
        fi
    
    - name: Attest pushed image
      uses: actions/attest-build-provenance@v2
      id: attest
      if: ${{ github.event_name != 'pull_request' }}
      with:
        subject-name: ${{ env.IMAGE_URL }}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: false
